# Generated by Django 4.2.1 on 2023-05-30 15:25

import app1.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=250)),
                ("image", models.ImageField(upload_to=app1.models.user_directory_path)),
                (
                    "image_caption",
                    models.CharField(default="Photo Demo", max_length=100),
                ),
                ("publish", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
